/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        /* ── Stitch Design System Exact Color Palette ── */
        'primary-fixed': '#e5e2e1',
        'tertiary-fixed': '#ffe082',
        'paper-base': '#F5F0E8',
        'border-tan': '#DDD8CE',
        'surface-container-low': '#f8f3eb',
        'secondary-grey': '#6B6B6B',
        'surface-container': '#f2ede5',
        'surface-bright': '#fef9f1',
        'surface': '#fef9f1',
        'on-secondary-fixed-variant': '#920023',
        'secondary-container': '#da3148',
        'inverse-on-surface': '#f5f0e8',
        'on-secondary-container': '#fffbff',
        'on-background': '#1d1c17',
        'on-error': '#ffffff',
        'status-verified': '#15803D',
        'status-reported': '#B45309',
        'status-disputed': '#C41E3A',
        'status-pending': '#6B7280',
        'on-tertiary-container': '#4d3e00',
        'tertiary-container': '#cba724',
        'surface-variant': '#e7e2da',
        'cat-statement': '#6D28D9',
        'background': '#fef9f1',
        'surface-white': '#FDFCF9',
        'on-surface': '#1d1c17',
        'on-tertiary-fixed': '#231b00',
        'cat-legal': '#B45309',
        'surface-tint': '#5f5e5e',
        'secondary': '#b71032',
        'error-container': '#ffdad6',
        'on-secondary': '#ffffff',
        'primary-container': '#1c1b1b',
        'on-primary-fixed': '#1c1b1b',
        'outline-variant': '#c4c7c7',
        'cat-loss': '#7F1D1D',
        'cat-violence': '#C41E3A',
        'on-surface-variant': '#444748',
        'on-primary': '#ffffff',
        'cat-ground': '#065F46',
        'on-primary-fixed-variant': '#474746',
        'secondary-fixed': '#ffdad9',
        'on-tertiary-fixed-variant': '#564500',
        'tertiary': '#725c00',
        'surface-container-lowest': '#ffffff',
        'on-error-container': '#93000a',
        'press-red': '#C41E3A',
        'surface-container-high': '#ece8e0',
        'primary': '#000000',
        'surface-dim': '#ded9d2',
        'secondary-fixed-dim': '#ffb3b4',
        'inverse-surface': '#32302b',
        'on-tertiary': '#ffffff',
        'inverse-primary': '#c8c6c5',
        'ink-black': '#1A1A1A',
        'error': '#ba1a1a',
        'primary-fixed-dim': '#c8c6c5',
        'cat-shutdown': '#1D4ED8',
        'archive-gold': '#B8960C',
        'on-primary-container': '#858383',
        'outline': '#747878',
        'on-secondary-fixed': '#40000a',
        'tertiary-fixed-dim': '#e9c340',
        'surface-container-highest': '#e7e2da',
        'surface-white-90': 'rgba(253,252,249,0.9)',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-desktop': '2.5rem',
        'container-max': '1600px',
        'section-gap': '4rem',
        'margin-mobile': '1rem',
        'gutter': '1.5rem',
      },
      fontFamily: {
        'edition-number': ['Inter', 'sans-serif'],
        'pull-quote': ['Playfair Display', 'serif'],
        'subheadline': ['Merriweather', 'serif'],
        'masthead-logo': ['Playfair Display', 'serif'],
        'label-tag': ['Inter', 'sans-serif'],
        'headline-md': ['Playfair Display', 'serif'],
        'caption': ['Inter', 'sans-serif'],
        'headline-lg': ['Playfair Display', 'serif'],
        'data-mono': ['JetBrains Mono', 'monospace'],
        'body-text': ['Merriweather', 'serif'],
      },
      fontSize: {
        'edition-number': ['12px', { lineHeight: '1', letterSpacing: '0.2em', fontWeight: '500' }],
        'pull-quote': ['32px', { lineHeight: '1.4', fontWeight: '700' }],
        'subheadline': ['18px', { lineHeight: '1.5', fontWeight: '600' }],
        'masthead-logo': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '900' }],
        'label-tag': ['11px', { lineHeight: '1', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '700' }],
        'caption': ['11px', { lineHeight: '1.4', letterSpacing: '0.08em', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '1.3', fontWeight: '700' }],
        'data-mono': ['13px', { lineHeight: '1.4', fontWeight: '400' }],
        'body-text': ['16px', { lineHeight: '1.8', fontWeight: '400' }],
      },
      maxWidth: {
        'container-max': '1600px',
      },
      animation: {
        'scan': 'scan 3s ease-in-out infinite',
        'ticker': 'ticker 30s linear infinite',
        'pulse-dot': 'pulse-dot 1.5s ease-in-out infinite',
      },
      keyframes: {
        scan: {
          '0%': { transform: 'translateY(-100%)', opacity: '0' },
          '10%': { opacity: '1' },
          '90%': { opacity: '1' },
          '100%': { transform: 'translateY(100vh)', opacity: '0' },
        },
        ticker: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        'pulse-dot': {
          '0%, 100%': { opacity: '1', transform: 'scale(1)' },
          '50%': { opacity: '0.5', transform: 'scale(0.85)' },
        },
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
